### ISSUE TITLE
template extending

### ISSUE THREAD

**Issue by oleggromov** [shaekuronen/grunt-ejs-static#2]
Hi! I'm just looking for an HTML-like template engine to compile many different html pieces into many other pages. EJS looks great and your grunt-ejs-static task too!

Include feature makes possible to include some partials into a single file, which is great, but extending is more likely to be correct for layouting. Imagine that I want to build 3 pages with different content but within one layout: main, blog and post.

Now I'm set to make 3 different so-called `layouts` looking pretty the same. The first one will include head.ejs, main.ejs and foot.ejs, the second one will have head.ejs, blog.ejs and foot.ejs included and the last one will have head.ejs, post.ejs and foot.ejs.

Instead of this duplication I'll be happy to make one layout with head and foot includes, then create there a `block` named `content` for example and then create pages. Each page may redefine this `block` using keyword `extend` with block name or something similar.

I realize EJS itself didn't have importing features before you made it.
Is it possible to make extending? May I help you with this job?
Thanks!

**Comment by shaekuronen** [comment]
This sounds like it could be a pretty cool feature.  EJS doesn't have blocks per se, so I've been looking at options for adding equivalent structure.  Would be great to see how you're thinking about implementing.

Do you have time to put together a pull request?

**Comment by oleggromov** [comment]
Not sure about pull request right now, sorry :(
I've found http://nunjucks.jlongster.com/ template engine that already has perfect template inheritance and extending. Nunjucks fits my needs, so I'm adapting to use it. Maybe EJS itself should have extending feature, shouldn't it? Or you're going to implement this absent feature only in grunt-ejs-static task?

**Comment by shaekuronen** [comment]
Thanks for the feedback Oleg!  Took a look at how Nunjucks handles inheritance http://jinja.pocoo.org/docs/templates/#template-inheritance

In Nunjucks, the base template contains blocks, which are chunks of the template that child templates can override.  

The same thing can be accomplished with this project, though the implementation is different.  The equivalent to the base template is the layout file, which can be re-used multiple times.  

First, create a layout file `default.ejs`

``` js
<% include ../templates/global/head %>

<% include ../templates/global/header %>

<% include ../templates/variable_content/router %>

<% include ../templates/global/footer %>

<% include ../templates/global/scripts %>

<% include ../templates/global/foot %>
```

Next create a router template `router.ejs`.  EJS does not seem to like switch statements, return, or if elses, so assigning file_name to false is used instead of of one of those options.

``` js
// case 1 
<% if (file_name === 'contact') { %>
  <% include ../contact/body %>
  <% file_name = false; %>
<% } %>
// end case 1

// case 2 
<% if (file_name === 'about') { %>
  <% include ../about/body %>
  <% file_name = false; %>
<% } %>
// end case 2 

// default case 
<% if (file_name) { %>
  <% include ../variable_content/default_content %>
<% } %>
// end default case 
```

The variable file_name is the key for each file which is defined in the main data file (in the demo, data/data.json).  For example, in `data.ejs`, you would define the layout like this

``` js
"contact": {
  "path_to_layout": "demo/dev/layouts/default.ejs",
  "meta": {
    "title": "Contact",
    "description": "Compile static html from ejs templates",
    "keywords": "gruntplugin, ejs, static html, static site generator"
  }
},
```

Thanks again and good luck with your project!
